packages:
  - 'packages/*'
  - 'playground/**'

catalog:
  'vue': ^3.5.27
  'vite': ^7.3.1
  'vue-router': ^5.0.2

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.3.1

overrides:
  '@vitejs/plugin-vue': workspace:*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - core-js
  - esbuild
  - less

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - playwright-chromium
  - simple-git-hooks
  - unrs-resolver

hoistPattern:
  - postcss
  - pug # playground/vue > @vue/compiler-sfc
  - ts-node # playground/tailwind

autoInstallPeers: false

strictPeerDependencies: false

shellEmulator: true
