packages:
  - 'packages/*'
  - 'playground/**'

catalog:
  'vue': ^3.5.22
  'vite': ^7.1.7
  'vue-router': ^4.5.1

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.1.15

overrides:
  '@vitejs/plugin-vue': workspace:*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - playwright-chromium
  - simple-git-hooks
  - unrs-resolver
