packages:
  - 'packages/*'
  - 'playground/**'

catalog:
  'vue': ^3.5.24
  'vite': ^7.1.10
  'vue-router': ^4.6.3

catalogs:
  rolldown-vite:
    vite: npm:rolldown-vite@^7.2.2

overrides:
  '@vitejs/plugin-vue': workspace:*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - core-js
  - esbuild

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - playwright-chromium
  - simple-git-hooks
  - unrs-resolver
