packages:
  - 'packages/*'
  - 'playground/**'

catalog:
  'vue': ^3.5.40
  'vite': ^8.1.5
  'vue-router': ^5.2.0

overrides:
  '@vitejs/plugin-vue': workspace:*

minimumReleaseAgeExclude:
  - '*'

allowBuilds:
  '@tailwindcss/oxide': true
  'playwright-chromium': true
  'simple-git-hooks': true
  'unrs-resolver': true
  '@parcel/watcher': false
  '@swc/core': false
  'core-js': false
  'esbuild': false
  'less': false

hoistPattern:
  - postcss
  - pug # playground/vue > @vue/compiler-sfc
  - ts-node # playground/tailwind

autoInstallPeers: false

strictPeerDependencies: false

shellEmulator: true

dedupePeers: true
